export const GET_IMAGES_REQUEST = "GET_IMAGES_REQUEST";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAIL = "GET_IMAGES_FAIL";
export const GET_IMAGES_RESET = "GET_IMAGES_RESET";

export const POST_IMAGE_REQUEST = "POST_IMAGE_REQUEST";
export const POST_IMAGE_SUCCESS = "POST_IMAGE_SUCCESS";
export const POST_IMAGE_FAIL = "POST_IMAGE_FAIL";
export const POST_IMAGE_RESET = "POST_IMAGE_RESET";

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL";
export const DELETE_IMAGE_RESET = "DELETE_IMAGE_RESET";
